### ISSUE TITLE
Setup AWS and app for attachments

### ISSUE THREAD

**Issue by ChilliCreek** [abdulkhalil54/Team-Sun#11]
**Task:**
- [ ] Set up a user on AWS, create an access key with the secret access key
- [ ] Make a tutorial for everybody on the credentials setup with the access key 
- [ ] Write a two functions that store and retrieve files from Amazon S3.
- [ ] Integrate with the application storage.
