### ISSUE TITLE
TASK: Student Portal 

### ISSUE THREAD

**Issue by DarzyD** [abdulkhalil54/Team-Sun#16]
Student Portal Features:

![image](https://user-images.githubusercontent.com/61167958/231065881-bfe5cf42-d6ed-4d7e-8f2b-fb9834b8472d.png)

**Comment by jinc0930** [comment]
Update:
![image](https://user-images.githubusercontent.com/39443822/233454642-8a9cabd2-35fe-4cc0-9442-70a12ead5590.png)

Next steps:
- [ ] left column?
- [ ] functional buttons ( actually does something when clicked)
- [ ] padding for table
- [ ] better format / aesthetics

**Comment by ChilliCreek** [comment]
Need to implement JS on the frontend side to retrieve information to display for the student page. Do we need better aethetics?

**Comment by asingh80** [comment]
**Task:** Update the student portal page with changes discussed in Tuesday's meeting: 
- [ ] Remove 'edit application' button. 
- [ ] Edit help button to inform students that, if they need to make any changes to their application, they can do so by submitting a new one. 
- [ ] Status column should be Accepted / Rejected / Pending. 
- [ ] 'New application' button should redirect to blank application page.

**Comment by jinc0930** [comment]
Done.  Waiting on backend API for student preferences so the sections can be ordered.

**Comment by jinc0930** [comment]
@DarzyD  Can we change the home button to white?
