### ISSUE TITLE
Find a way to send files from frontend to backend

### ISSUE THREAD

**Issue by asingh80** [abdulkhalil54/Team-Sun#6]
**Task:** Planning out how the backend is going to operate in terms of program structure, so that everyone working on back-end is on the same page in terms of retrieving and working with data. 
**For example:** We'll have 1 class for Students and 1 class for Professors. 

Questions to be answered: 
- [x] How are we going to deal with attachments? What will their data type be? 
- [ ] Will students be allowed to submit more than 1 attachment? (In which case, we'd have to make the attachments attribute as some form of a list.) Should there be an upper limit, e.g. 5 attachments?
- [ ] Will there be an upper limit on the number of references?

**Comment by asingh80** [comment]
**OVERVIEW:** Classes are Student, Professor, Application, Section.
Student and Professor each have Username and Password attributes.
Student has Application, Professor has Section.
Section Object has separate attributes for Day and Time to conveniently compare against student’s preferred days and times. 

**CLASS: Student**
- ATTRIBUTE: Username (String)
- ATTRIBUTE: Password (String)
- ATTRIBUTE: Application (Object)
- METHODS: getUsername, getPassword, getApplication.

**CLASS: Professor**
- ATTRIBUTE: Username (String)
- ATTRIBUTE: Password (String)
- ATTRIBUTE: Sections (list of Objects of type Section)
- METHODS: getUsername, getPassword, getSections.

**CLASS: Application**
- ATTRIBUTE: Name (String)
- ATTRIBUTE: Year (String) 
- ATTRIBUTE: GPA (Float)
- ATTRIBUTE: Grade in 320 (Char)
- ATTRIBUTE: References (List of name-contact / String-String pairs)
- ATTRIBUTE: Resume Attachment (File? List of files?)
- METHODS: getName, getYear, getGPA, getGradeIn320, getAttachment(s), getReferences.

**CLASS: Section**
- ATTRIBUTE: Section Number (Integer)
- ATTRIBUTE: Day (String)
- ATTRIBUTE: Time (String)
- ATTRIBUTE: Professor Name (String)
- ATTRIBUTE: Capacity (Integer)
- ATTRIBUTE: numEnrolled (Integer)
- METHODS: getSectionNumber, getDay, getTime, getProfessorName, getCapacity, getNumEnrolled. 

**MAIN CLASS:** not an Object class, just the main class where everything else is called from.
- ATTRIBUTE: applicationsList -- holds all Objects of type Application (for when the Professors want to see the application pool in some way). 
- ATTRIBUTE: sectionsList -- holds all Objects of type Section (for the potential Announcement page). 
- ATTRIBUTE: Matchings (list) -- this will store the final Student-Section matching. 
- METHOD: createMatching -- this is the matching algorithm.

**Comment by asingh80** [comment]
Link to working document for this issue: https://docs.google.com/document/d/1z-Z58rW-Xdew83wvPGd9tVbAn_aHinVFYNT-dAksUoA/edit

**Comment by jinc0930** [comment]
Here is some preliminary thoughts:

we can give each document a number(docID) which will then be stored in a database, all together, and each user will have an array of docID associated with them, if we need to view the document we will then fetch it from the database

we should give a limit on how many documents one can submit to avoid overburdening the database, I like 5, but perhaps even 3 would do. -- THIS also wouldn't be too much of user trouble if we ask students submit all their documents in one file/zip

same with references -- should be limited, but on the topic of this:
- [ ] will there be a references account type where the references can submit any recommendation letters or supplemental materials??
- [ ] If more than one student has the same reference, how can we separate that?
